// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQ2yJDGvJK1h-5GRZR0zScFJ8GTi-YWI',
    appId: '1:826928035408:web:03a58ab720b8cc195e0355',
    messagingSenderId: '826928035408',
    projectId: 'educonnect-3da1d',
    authDomain: 'educonnect-3da1d.firebaseapp.com',
    storageBucket: 'educonnect-3da1d.firebasestorage.app',
    measurementId: 'G-D3HTQXTGD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiFjF5u3HOl9G5Z22WRxJApmZgL1MiJow',
    appId: '1:826928035408:android:c855c044ef209aa05e0355',
    messagingSenderId: '826928035408',
    projectId: 'educonnect-3da1d',
    storageBucket: 'educonnect-3da1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRgeoGlqOH_TEkZMgk62labafqsXYbVQ',
    appId: '1:826928035408:ios:353bacfb51578a3e5e0355',
    messagingSenderId: '826928035408',
    projectId: 'educonnect-3da1d',
    storageBucket: 'educonnect-3da1d.firebasestorage.app',
    iosClientId: '826928035408-e6f3cf054lavb8gls4klda4u2cbvhobi.apps.googleusercontent.com',
    iosBundleId: 'com.educonnect.saufi.nazrin.educonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRgeoGlqOH_TEkZMgk62labafqsXYbVQ',
    appId: '1:826928035408:ios:353bacfb51578a3e5e0355',
    messagingSenderId: '826928035408',
    projectId: 'educonnect-3da1d',
    storageBucket: 'educonnect-3da1d.firebasestorage.app',
    iosClientId: '826928035408-e6f3cf054lavb8gls4klda4u2cbvhobi.apps.googleusercontent.com',
    iosBundleId: 'com.educonnect.saufi.nazrin.educonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQ2yJDGvJK1h-5GRZR0zScFJ8GTi-YWI',
    appId: '1:826928035408:web:acf1bee1390afe3d5e0355',
    messagingSenderId: '826928035408',
    projectId: 'educonnect-3da1d',
    authDomain: 'educonnect-3da1d.firebaseapp.com',
    storageBucket: 'educonnect-3da1d.firebasestorage.app',
    measurementId: 'G-HV417702KQ',
  );
}
